//
//  EditJournalResultPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-03-02
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientJournal.h>
#import <APSDK/Mood.h>
#import <APSDK/Ability.h>
#import "BaseFormViewController.h"
#import <APSDK/UserProfile.h>
#import <APSDK/PatientJournalQuestionnaire.h>
#import "FormInputTextField.h"
#import <APSDK/MissingTreatmentReason.h>
#import "QuestionnaireViewController.h"

@class EditJournalResultPageViewController;

@protocol EditJournalResultPageViewControllerDelegate <NSObject>
-(void)userInteractedWithViewController:(EditJournalResultPageViewController *)controller;
@end


@interface EditJournalResultPageViewController : BaseFormViewController {
}

@property (nonatomic, strong) PatientJournal * patientJournal;
@property (nonatomic, strong) PatientJournalQuestionnaire * patientQuestionnaire;

@property (nonatomic, strong) UserProfile * userProfile;

@property (strong, nonatomic) NSArray *patientSymptomData;
@property (strong, nonatomic) NSMutableArray *selectedSymptomData;
@property (strong, nonatomic) NSString *selectedSymptomIds;
@property (nonatomic, strong) NSArray * dayRatingData;
@property (nonatomic,strong) NSArray * timeFrameData;
@property (nonatomic, strong) NSArray * painRatingData;
@property (strong, nonatomic) Mood *mood;
@property (strong, nonatomic) Ability *ability;
@property (strong, nonatomic) NSNumber *dayRating;
@property (nonatomic, strong) NSNumber * timeFrame;
@property (strong, nonatomic) NSNumber *painRating;


@property (nonatomic, weak) id <EditJournalResultPageViewControllerDelegate> delegate;
//@property (strong, nonatomic) NSNumber *symptomsToday;
//@property (strong, nonatomic) MedicationTakenToday *medicationTakenToday;

//- Svaz added for Medication treatment
- (IBAction)toggleTookMedication;
//@property (strong, nonatomic) MissingTreatmentReason *missingTreatmentReason;
//@property (strong, nonatomic) MissingTreatmentReason *missingTimesReason;
//@property (nonatomic, strong) NSArray * dayMissedData;
//@property (strong, nonatomic) NSNumber *dayMissed;

@property (weak, nonatomic) IBOutlet UIButton *logsButton;
//- (IBAction)loadLogs;
- (IBAction)saveTapped;
// end added -svaz

@property (nonatomic, strong) NSNumber * peakFlow;
@property (nonatomic, strong) NSNumber * allergensToday;
@property (nonatomic, strong) NSNumber * inhaler;
@property (nonatomic, strong) NSNumber  * shortnessBreath;

@property (nonatomic, strong) NSNumber * fvc;
@property (nonatomic, strong) NSNumber * fvcPercentage;

@property (nonatomic, strong) NSNumber * fev;
@property (nonatomic, strong) NSNumber * fevPercentage;

@property (nonatomic, strong) NSNumber * fef;
@property (nonatomic, strong) NSNumber * fevFvc;

//for PD --rvera 10/21/14
@property (strong, nonatomic) NSNumber *dyskinesiaRating;
@property (nonatomic, strong) NSArray * dyskinesiaRatingData;
@property (nonatomic, strong) NSNumber  * dyskinesiaDayPercentage;

//BC -- 11-18-14
@property (strong, nonatomic) NSNumber *cognitiveDifficulty;
@property (nonatomic, strong) NSArray * cognitiveDifficultyData;
@property (strong, nonatomic) NSNumber *difficultyEverydayActivity;
@property (nonatomic, strong) NSArray * difficultyEverydayActivityData;

//@property (nonatomic, weak) IBOutlet NSString * notes;


@end
