//
//  EditJournalResultPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-03-02
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientJournal.h>
#import <APSDK/Mood.h>
#import <APSDK/Ability.h>
#import "BaseFormViewController.h"
#import <APSDK/UserProfile.h>

@class EditJournalResultPageViewController;

@protocol EditJournalResultPageViewControllerDelegate <NSObject>
-(void)userInteractedWithViewController:(EditJournalResultPageViewController *)controller;
@end


@interface EditJournalResultPageViewController : BaseFormViewController {
}

@property (nonatomic, strong) PatientJournal * patientJournal;
@property (nonatomic, strong) UserProfile * userProfile;

@property (strong, nonatomic) NSArray *patientSymptomData;
@property (strong, nonatomic) NSMutableArray *selectedSymptomData;
@property (strong, nonatomic) NSString *selectedSymptomIds;
@property (nonatomic, strong) NSArray * dayRatingData;
@property (strong, nonatomic) Mood *mood;
@property (strong, nonatomic) Ability *ability;
@property (strong, nonatomic) NSNumber *dayRating;
@property (nonatomic, weak) id <EditJournalResultPageViewControllerDelegate> delegate;
//@property (strong, nonatomic) NSNumber *symptomsToday;
//@property (strong, nonatomic) MedicationTakenToday *medicationTakenToday;




@end