//
//  EditExacerbationPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientExacerbation.h>
#import <APSDK/Symptom.h>
#import "BaseFormViewController.h"

@class EditExacerbationPageViewController;

@protocol EditExacerbationPageViewControllerDelegate <NSObject>
-(void)userInteractedWithViewController:(EditExacerbationPageViewController *)controller;
@end

@interface EditExacerbationPageViewController : BaseFormViewController {
}

@property (nonatomic, strong) PatientExacerbation * patientExacerbation;

@property (strong, nonatomic) Symptom *symptom;
@property (strong, nonatomic) NSNumber *intensity;
@property (nonatomic, weak) id <EditExacerbationPageViewControllerDelegate> delegate;
@property (nonatomic, strong) NSArray * intensityData;



@end