//
//  EditSideEffectContentPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientSideEffect.h>
#import "BaseFormViewController.h"
#import <APSDK/SideEffect.h>

@class EditSideEffectContentPageViewController;

@protocol EditSideEffectContentPageViewControllerDelegate <NSObject>
-(void)userInteractedWithViewController:(EditSideEffectContentPageViewController *)controller;
@end



@interface EditSideEffectContentPageViewController : BaseFormViewController <UIPickerViewDataSource,UIPickerViewDelegate>{
}

@property (nonatomic, strong) PatientSideEffect * patientSideEffect;

@property (strong, nonatomic) NSString *selectedMedicationIds;
@property (strong, nonatomic) NSMutableArray *selectedMedicationsData;
@property (strong, nonatomic) NSArray *patientTreatmentMedicationData;
@property (strong, nonatomic) NSArray *patientSideEffectMedicationData;
@property (nonatomic, weak) id <EditSideEffectContentPageViewControllerDelegate> delegate;

@property (strong, nonatomic) SideEffect *sideEffect;

- (IBAction)doneBarButtonItemTapped;

@end
