//
//  EditJournalPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientJournal.h>

@interface EditJournalPageViewController : UIViewController {
}

@property (nonatomic, strong) PatientJournal * patientJournal;

@end
