//
//  HomePageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "CustomBadge.h"


@interface HomePageViewController : UIViewController <UIAlertViewDelegate>

@property (nonatomic) CustomBadge *notificationAlert;
-(IBAction)makeEmergencyCall:(id)sender;
@end
