//
//  JournalListViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientJournal.h>
#import "BaseTableViewController.h"
#import "EditJournalResultPageViewController.h"
//#import "FatigueDetailTableViewController.h"

@interface JournalListViewController : BaseTableViewController <EditJournalResultPageViewControllerDelegate> {
}
@property (nonatomic, assign) bool reloadDataOnLoad;


@end
