//
//  LabResultsListViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientLabResult.h>
#import "BaseTableViewController.h"
#import "EditLabResultPageViewController.h"


@interface LabResultsListViewController : BaseTableViewController <EditLabResultPageViewControllerDelegate> {
}


@property (strong, nonatomic) NSMutableDictionary *labStatuses;
@property (nonatomic, assign) bool reloadDataOnLoad;



@end
