//
//  MedicalHistoryPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/UserProfile.h>


@interface MedicalHistoryPageViewController : UIViewController {
}


@property (nonatomic, strong) UserProfile * userProfile;



@end
