//
//  MedicalConditionsPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "BaseTableViewController.h"

@interface MedicalConditionsPageViewController : BaseTableViewController {
}
@property (nonatomic, assign) BOOL reloadAll;
@property (strong, nonatomic) NSArray *medicalConditionData;

@end
