//
//  SideEffectListViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientSideEffect.h>
#import "BaseTableViewController.h"
#import "EditSideEffectContentPageViewController.h"
#import "APToolBar.h"

@interface SideEffectListViewController : BaseTableViewController <EditSideEffectContentPageViewControllerDelegate> {
}
@property (strong, nonatomic) NSArray *patientTreatmentMedicationData;
@property (nonatomic, assign) bool reloadDataOnLoad;


@end
