//
//  TreatmentListPageViewController.m
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-03-02
//  Copyright (c) 2013. All rights reserved.
//

#import <APSDK/AuthManager.h>
#import <APSDK/PatientTreatment+Remote.h>
#import <APSDK/User.h>
#import <APSDK/MissingTreatmentReason.h>
#import "AuthManager+Rules.h"
#import "LoadingTableViewCell.h"
#import "MBProgressHUD.h"
#import "TreatmentListPageViewController.h"
#import "UIView+APViewExtensions.h"
#import "UIViewController+UI.h"
#import "UpdateTreatmentPageViewController.h"
#import "DatedContentCell.h"
#import "UIColor+APColorExtension.h"
//#import "APNavigationController.h"
#import <APSDK/APObject+Remote.h>
#import <APSDK/APObject+RemoteRelationships.h>
#import "Arrow.h"
#import "ConfigurationManager.h"
#import "PIKCommon.h"
#import "PikConstants.h"


@interface TreatmentListPageViewController ()

@property (nonatomic, weak) IBOutlet UIBarButtonItem * addTreatmentButtonBarButtonItem;

- (IBAction)addTreatmentButtonTapped;
- (void)reloadTreatmentListPageDataAnimated:(BOOL)animated;

@end

@implementation TreatmentListPageViewController

@synthesize reloadDataOnLoad;


#pragma mark - Actions

- (IBAction)addTreatmentButtonTapped {
    [self.toolBar showHideToolBarInView:self.view animated:YES];
    if(self.toolBar.hidden) [self.tableView setEditing:NO animated:YES];
}

-(void)toolBarAdd{
    [self performSegueWithIdentifier:@"ShowAddTreatmentPageViewController" sender:self];
    [self.toolBar hideToolBarInView:self.view animated:NO];
    [self.tableView setEditing:NO animated:YES];
    [self.tutorialView dismissViewAnimated:NO completion:nil];
}
-(void)toolBarDelete{
    [self.tableView setEditing:!self.tableView.editing animated:YES];
}

//added for HepC --rvera9/4/14
- (IBAction)buttonPressedTreatmentMsg{
    UIAlertView *alertMsg = [[UIAlertView alloc]initWithTitle: nil // @"ALERT!"
                                                      message: @"“Please consult with your medical provider before taking any new prescription or over-the-counter medications, supplements, or herbals.”"
                                                     delegate: nil
                                            cancelButtonTitle:@"OK"
                                            otherButtonTitles:nil];
    [alertMsg show];
    NSLog(@"Button Pressed Message Tapped");
}

#pragma mark - Private


-(void)sortData
{
    self.sectionedTableData = [[NSMutableDictionary alloc] init];
    
    BOOL found;
    
    for (PatientTreatment *treatment in self.tableData) {
        found = NO;
        //see if we already have the category
        NSNumber *treatmentTypeId = treatment.treatmentTypeId;
        NSString *category = [[NSString alloc]init];
        AppDelegate *ad = (AppDelegate *)[[UIApplication sharedApplication]delegate];
        for(TreatmentType *tt in ad.treatmentTypeData){
            if([treatmentTypeId isEqualToNumber:tt.id]){
                category = [tt.sortId stringValue];
                break;
            }
        }
        
        for (NSString *sectionLabel in [self.sectionedTableData allKeys]) {
            if ([sectionLabel isEqualToString:category]) {
                found = YES;
                break;
            }
        }
        //category was not found so create a new array for it
        if (!found) {
            [self.sectionedTableData setValue:[[NSMutableArray alloc] init] forKey:category];
            
        }
        
        [[self.sectionedTableData objectForKey:category] addObject:treatment];
    }
    
    // Sort each section array
    for (NSString *key in [self.sectionedTableData allKeys])
    {
        NSSortDescriptor *treatmentSortDescriptor = [[NSSortDescriptor alloc] initWithKey:@"treatmentTypeDenormalized" ascending:YES];
        NSSortDescriptor *nameSortDescriptor = [[NSSortDescriptor alloc] initWithKey:@"medicationDenormalized" ascending:YES];
        NSArray *sortDescriptors = @[treatmentSortDescriptor,nameSortDescriptor];
        [[self.sectionedTableData objectForKey:key] sortUsingDescriptors:sortDescriptors];
    }
    [self.tableView reloadData];
}


- (void)reloadTreatmentListPageDataAnimated:(BOOL)animated
{
    
    if ([AppDelegate hasConnectivity])
    {
        [self pushBusyOperation];
        [PatientTreatment query:@"my_unarchived_treatments" params:nil async:^(NSArray * objects, NSError * error) {
            if (self.navigationController.topViewController == self) {
            if (error) {
                [self popBusyOperation];
                if(ERROR_CODE_401(error)) {
                    AppDelegate *app = (AppDelegate *)[[UIApplication sharedApplication] delegate];
                    [app showSessionTerminatedAlert];
                }
                else [self showMessage:[error localizedDescription] ? : @"Error"];
            }
            else{
                
                [self.tableData removeAllObjects];
                [self.tableData addObjectsFromArray:objects];
                [self sortData];
                [self.tableView reloadData];
//            - ios 8cleanup svaz 1/12/15
//                [self resize:self.tableView
//                          to:CGSizeMake(CGRectGetWidth(self.tableView.frame),
//                                        self.tableData.count * self.tableView.rowHeight + [self numberOfSectionsInTableView:self.tableView] * 24)
//                    animated:animated];
//            - ios 8 cleanup svaz 1/12/15  -end
                [self popBusyOperation];
//                if(!HAS_DATA){
//                    [self.toolBar showToolBarInView:self.view animated:NO];
//                    //   HIDE TUTORIAL FOR IPAD         -  MSAA cleanup svaz 11/27/14
//                    int tutorialX = 0;
//                    if (IS_IPAD) {
//                        tutorialX =+150;
//                        }
//                        CGRect frame = self.view.bounds;
//                        frame.origin.y += self.toolBar.frame.size.height;
//
//                        self.tutorialView = [[TutorialView alloc]initWithFrame:frame];
//                        [self.view addSubview:self.tutorialView];
//                        
//                        UILabel *newLabel = [[UILabel alloc]initWithFrame:CGRectMake(30+tutorialX, 200, 300, 40)];
//                        newLabel.text = @"Tap to start adding treatments";
//                        newLabel.backgroundColor = [UIColor clearColor];
//                        newLabel.textColor = [UIColor whiteColor];
//                        [self.tutorialView addSubview:newLabel];
//                        
//                        Arrow *newArrow = [[Arrow alloc]init];
//                        newArrow.head = CGPointMake(105+tutorialX, 5);
//                        newArrow.tail = CGPointMake(105+tutorialX, 200);
//                        [self.tutorialView addArrow:newArrow];
////
//                }

            }
            } else [self popBusyOperation];

        }];
    }
    else
    {
        [AppDelegate showNoConnecttivityAlert];
    }
}


#pragma mark - UITableViewDataSource



- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return [[self.sectionedTableData valueForKey:[[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:section]] count];
}

 
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (tableView == self.tableView) {

        DatedContentCell * cell = [tableView dequeueReusableCellWithIdentifier:@"Default"];
        
        //            -  MSAA cleanup svaz 11/27/14
//        cell.frame = CGRectMake(0,0,768,44);
        //        end    -  MSAA cleanup svaz 11/27/14
       
        PatientTreatment * object = [[self.sectionedTableData valueForKey:[[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:indexPath.section]] objectAtIndex:indexPath.row];
        NSString *dateString = [[self dateFormatterWithTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"UTC"]] stringFromDate:object.startOn];
        
        //*****         -  iOs 8 cleanup svaz 1/16/2015   -  To move cell from left edge
//        CGRect frame = cell.dateLabel.frame;
//        frame.origin.x=40;
//        cell.dateLabel.frame = frame;
        //   *****         -  iOs 8 cleanup svaz 1/16/2015   -end
        
        cell.dateLabel.text =  dateString;
        //Medication has a leading space so that it sorts to the top of the listing
        cell.contentLabel.text = object.treatmentScheduleDenormalized;
        if ([object.treatmentTypeId isEqualToNumber:@1]) {
            cell.contentLabel.text = object.medicationDenormalized;
        }
        else {
            cell.contentLabel.text = object.treatmentScheduleDenormalized;
        }
        
        cell.accessoryType =  UITableViewCellAccessoryDisclosureIndicator;
        cell.selectionStyle = UITableViewCellSelectionStyleGray;
        
         NSLog(@"cellforrow cell frame = %@",NSStringFromCGRect(cell.frame ));
       
//        NSLog(@"cell.dateLabel- cell frame = %@",NSStringFromCGRect(cell.dateLabel.frame ));
//        NSLog(@"contentLabel- cell frame = %@",NSStringFromCGRect(cell.contentLabel.frame ));
//        
//        
//        NSLog(@"tableView:- cell frame = %@",NSStringFromCGRect(cell.frame ));
        
        return cell;
    }
    
    return nil;
}

//- (void)tableView:(UITableView *)tableView  willDisplayCell:(UITableViewCell *)cell
//        forRowAtIndexPath:(NSIndexPath *)indexPath{
//    
//    //            -  MSAA cleanup svaz 11/27/14
//    cell.frame = CGRectMake(0,0,320,24);
//    //        end    -  MSAA cleanup svaz 11/27/14
//    
//      NSLog(@"willDisplayCell cell frame = %@",NSStringFromCGRect(cell.frame ));
//}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    //   *****         -  iOs 8 cleanup svaz 1/23/2015   -end
//    return 44.0;
    return kRowHeight;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    
    return [[self.sectionedTableData allKeys] count];
}


#pragma mark - UITableViewDelegate

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (tableView == self.tableView) {
        
        PatientTreatment *treatment = [[self.sectionedTableData valueForKey:[[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:indexPath.section]] objectAtIndex:indexPath.row];
        
        [self performSegueWithIdentifier:@"ShowUpdateTreatmentPageViewController" sender:treatment];
    }
}


- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    UIView *headerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 24)];
    headerView.backgroundColor = [UIColor darkBlue];
    
    UILabel *sectionTitle = [[UILabel alloc] initWithFrame:CGRectMake(10, 2, 320, 20)];
    sectionTitle.textColor = [UIColor whiteColor];
    sectionTitle.backgroundColor = [UIColor clearColor];
    /*sectionTitle.text = [[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:section];*/
    
    AppDelegate *ad = (AppDelegate *)[[UIApplication sharedApplication]delegate];
    NSString * sortId = [[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:section];
    NSNumberFormatter * f = [[NSNumberFormatter alloc] init];
    [f setNumberStyle:NSNumberFormatterDecimalStyle];
    
    for(TreatmentType *tt in ad.treatmentTypeData){
        if([[f numberFromString:sortId] isEqualToNumber:tt.sortId])
        {
            sectionTitle.text = tt.name;
            break;
        }
    }
    
    [headerView addSubview:sectionTitle];
    
    return headerView;
}


- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    return 24;
}

- (UITableViewCellEditingStyle)tableView:(UITableView *)tableView
           editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath
{
        return UITableViewCellEditingStyleDelete;
}

- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (editingStyle == UITableViewCellEditingStyleDelete) {
        
        if ([AppDelegate hasConnectivity])
        {
            PatientTreatment * patientTreatment = [[self.sectionedTableData valueForKey:[[[self.sectionedTableData allKeys] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)] objectAtIndex:indexPath.section]] objectAtIndex:indexPath.row];
            
            
            patientTreatment.archived = @1;//true
            [self pushBusyOperation];
            __unsafe_unretained TreatmentListPageViewController * _self = self;

            [patientTreatment updateAsync:^(id obj, NSError * error) {
                if (error) {
                    [_self popBusyOperation];
                    if(ERROR_CODE_401(error)) {
                        AppDelegate *app = (AppDelegate *)[[UIApplication sharedApplication] delegate];
                        [app showSessionTerminatedAlert];
                    }
                    else [_self showMessage:@"Treatment record failed to delete."];
                } else {
                    [_self popBusyOperation];
                    //[_self showMessage:@"Treatment record successfully deleted."];
                    [UIView transitionWithView: self.tableView
                                      duration: 0.35f
                                       options: UIViewAnimationOptionTransitionCrossDissolve
                                    animations: ^(void)
                     {
                         [_self reloadTreatmentListPageDataAnimated:YES];
                     }
                                    completion: ^(BOOL isFinished)
                     {
                     }];
                }
            }];
        }
        else
        {
            [AppDelegate showNoConnecttivityAlert];
        }
    }
}



#pragma mark - UIViewController

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    if ([segue.identifier isEqualToString:@"ShowUpdateTreatmentPageViewController"]) {
        ((UpdateTreatmentPageViewController *)segue.destinationViewController).patientTreatment = sender;
        ((UpdateTreatmentPageViewController *)segue.destinationViewController).editMode = YES;
        ((UpdateTreatmentPageViewController *)segue.destinationViewController).delegate = self;
    }
    else if ([segue.identifier isEqualToString:@"ShowAddTreatmentPageViewController"]) {
        UpdateTreatmentPageViewController *controller = (UpdateTreatmentPageViewController *)[((UINavigationController *)segue.destinationViewController).viewControllers objectAtIndex:0];
        controller.editMode = NO;
        controller.delegate = self;
    }
}

-(void)viewDidLoad{
    [super viewDidLoad];
    self.navigationItem.title = [AppDelegate interpolateString:NSLocalizedString(@"My Treatment", @"My Treatment")];
    reloadDataOnLoad = YES;    
    //added a new message --rvera 9/4/14
    if ([[[ConfigurationManager sharedManager] appID] integerValue] == HepC)
    {
        [self buttonPressedTreatmentMsg];
    }
    //            -  MSAA cleanup svaz 11/27/14
    self.tableView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
    self.tableView.frame = self.view.bounds;
   //        end    -  MSAA cleanup svaz 11/27/14
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [self addObservers];
    if(reloadDataOnLoad){
        [self reloadTreatmentListPageDataAnimated:animated];
        reloadDataOnLoad = NO;
    }
}

#pragma mark - Data

-(void)loadDataFromAppDelegate {
    AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    
    if (![appDelegate finishedLoadingReferenceData]) {
        //[appDelegate loadReferenceData];
    }

}

-(void)userInteractedWithViewController:(UpdateTreatmentPageViewController *)controller {
    self.reloadDataOnLoad = YES;
}

@end
