//
//  TreatmentListPageViewController.h
//  MSPatient
//
//  Generated by AnyPresence, Inc on 2013-03-02
//  Copyright (c) 2013. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <APSDK/PatientTreatment.h>
#import "BaseTableViewController.h"
#import "UpdateTreatmentPageViewController.h"
#import "APToolBar.h"

@interface TreatmentPickPageViewController : BaseTableViewController <UpdatePatientPageViewControllerDelegate> {
}

@property (strong, nonatomic) NSMutableDictionary *sectionedTableData;
@property (nonatomic, assign) bool reloadDataOnLoad;
@property (nonatomic, assign) int chartId;

-(IBAction)closeButtonTapped:(id)sender;

@end
