//
//  main.m
//  
//
//  Generated by AnyPresence, Inc on 2013-02-26
//  Copyright (c) 2013. All rights reserved.
//
//
//---------------------------------------------------------------------------
// Savio, I added this coimment to check if you see them!!! -- RV
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
// Savio, I added this coimment to check if you see them!!! -- RV
//---------------------------------------------------------------------------


#import <UIKit/UIKit.h>


#import "AppDelegate.h"
// Comment 

int main(int argc, char *argv[])
{
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}
